### ISSUE TITLE
Mouse cursor lagging while connected to Miniscope V4

### ISSUE THREAD

**Issue by obarnstedt** [bothlab/pomidaq#15]
Hi,
I have just installed pomidaq on Ubuntu 24.04 without problems and it runs perfectly fine with a Miniscope V4 (Daq box v3.3), but unfortunately once connected, the mouse cursor starts lagging, until it's disconnected. I suspect the graphics might be an issue but the workstation's hardware is up-to-date and OpenGL 4.6 is installed. I also tried compiling pomidaq which improved the GUI but the cursor still keeps lagging once it's connected. Any ideas of what the culprit could be?
Thanks,
Oliver

**Comment by ximion** [comment]
That is a very weird issue, I have never seen this behavior on any PC or laptop.
Is the cursor lagging in general, or only on the PoMiDAQ window?

If it is lagging everywhere and your mouse is attached via a USB port, please try a different USB port. We did observe that if there are too many high-datarate devices on the same USB hub, sometimes low-speed devices like mice on the same hub get the short end of the stick and we do get cursor lag.

This has never happened with the Miniscope though (which doesn't actually send that much data), so this is still fairly odd (the way PoMiDAQ is designed, UI events are also complete separate from DAQ processing, so a running Miniscope should never impact the UI (and cursors, if they are drawn by the app with GNOME's Mutter compositor in case you are on Wayland instead of X11)).

**Comment by obarnstedt** [comment]
Hi,
thanks for the tip. Indeed, changing USB ports solved the problem.
It's working great now!
