### ISSUE TITLE
Miniscope V4 compatible

### ISSUE THREAD

**Issue by ChangQing-SH** [bothlab/pomidaq#2]
Hi,

Does Pomidaq support the miniscope V4? 
btw, Does the libminiscope use the UCLA daq library,  and then the GUI build on the pyqt?

**Comment by ximion** [comment]
So, the current Git master version works with v4 Miniscopes in theory - since I don't have one yet, I couldn't test the support yet, but I don't see a reason why it wouldn't work.
To use the v4 or v3 Miniscopes with PoMiDAQ and the newer firmware on Linux though, you will need the firmware patch from https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/pull/2 applied.

There is no UCLA daq library that I am aware of. PoMiDAQ itself is comprised of a shared library which handles all the Miniscope communication (libminiscope) written in C++ that the GUI (also C++) is using. On Windows, the shared lib doesn't exist and is compiled right into the binary.
The Python bindings, which are not yet updated in Git master for the new v4 Miniscope code, also use the same C++ library and are just a thin layer translation layer to make Miniscope data available in Numpy arrays efficiently.

Depending on what you want to do, using building Git master is worth a try (if you do need Python support, it's worth to wait a bit though, as that isn't ready yet - the shared library uses Qt for external interfaces now, and the binding generation needs to be adjusted for that).

**Comment by ChangQing-SH** [comment]
Thanks for your reply,  I am assembling the Miniscope V4, I'll do some testing, 
btw, It's better to make a wiki about the installation, the library document, etc, like the UCLA's,  it might be more friendly to the user.

**Comment by ximion** [comment]
I'm currently a bit busy to create another wiki, especially since the README file already covers most ground (and will be extended a bit as well, soon). But, PRs to add more documentation are appreciated.

**Comment by ximion** [comment]
The v4 Miniscope support is complete now. Just needs wider testing, and for that there will be a new release soon.
