### ISSUE TITLE
v0.40-git180 Unable to get valid timestamps for initialization

### ISSUE THREAD

**Issue by WuKaiibin** [bothlab/pomidaq#4]
I got the latest DAQ and V4 miniscope. When I try to connect it to v4, it said  Unable to get valid timestamps for initialization, How to solve this problem?

**Comment by ximion** [comment]
Is this on Windows or on Linux? It basically means the driver is providing invalid timestamps, usually a bunch of zeros in a row for time. Please double-check that you have the right camera ID selected as well for this.

**Comment by WuKaiibin** [comment]
It is on Win10. Th deviceID works fine on the orignal miniscope DAQ software. The v0.4 always says Unable to get valid timestamps for initialization.

**Comment by ximion** [comment]
This is due to a safety-check in PoMiDAQ which forces the driver to deliver accurate timestamps (> 0) before it considers the Miniscope to actually be usable.
I need to try this on a Windows box later once I get my hands on one again, and see what is going on... You could try using the freshly built experimental executable from https://github.com/bothlab/pomidaq/actions/runs/423810267 if you have permission to download build artifacts (I think they should be accessible for people logged into GitHub). That build contains a change where the software will simply wait a bit longer (2 seconds) for good timestamps to appear.

**Comment by ximion** [comment]
I resolved this by changing the capture backend on Windows and also adding an automatic fallback to emulated timestamps on Windows (the log contains information on what is used and why).
I will run a small test tomorrow to ensure the emulated timestamps close in accuracy to the other ones (likely the case) and then make a new release.
Thank you for reporting this issue!

**Comment by ximion** [comment]
New release is out now: https://github.com/bothlab/pomidaq/releases/tag/v0.4.1
