### ISSUE TITLE
PoMiDAQ-0.4.1+git198: No sync pulse output from the sync SMA connector

### ISSUE THREAD

**Issue by guoqingchun30** [bothlab/pomidaq#5]
Hi, I'm testing the PoMiDAQ-0.4.1+git198 software with my miniscope V3 & DAQ V3.2. The sync port  (J5) on the DAQ board (V3.2) has always been a high-level output instead of a series of pulses. Have you met this issue? Or it is just because the PoMiDAQ-0.4.1+git198 doesn't support the sync function in the current version.

**Comment by ximion** [comment]
The pulses are generated by the DAQ hardware, without control of the software. PoMiDAQ doesn't support being triggered by input pulses, but sync output pulses should always appear.

I'll have a look at this, I can't fully rule out that this is a software issue (maybe some new flag has to be sent to the DAQ box). But please check also if this DAQ board exhibits the same behavior with the UCLA software, just to rule out any hardware issues.

**Comment by guoqingchun30** [comment]
Hi, I do test this on two different software platforms using the same hardware. As shown in the following figure. The sync signal is normal in the UCLA software. But there is no output when changed to the PoMiDAQ-0.4.1.
![image](https://user-images.githubusercontent.com/55228883/102445780-48ac6980-4067-11eb-973a-a226ca61ff92.png)

**Comment by ximion** [comment]
That was indeed an error - apparently support was dropped in the past due to issues with the older firmware on Linux, but these Problems no longer exist (and that feature wasn't restored for some reason).
Anyway, it's fixed now and you can get a fresh build from the CI system @ https://github.com/bothlab/pomidaq/actions/runs/428288461
Thank you for the issue report!
