### ISSUE TITLE
the video window doesn't show on the GUI

### ISSUE THREAD

**Issue by ChangQing-SH** [bothlab/pomidaq#8]
it works at the beginning, but I don't know why, when I open it again, the GUI only shows the setting window, without the video window, 
OS: Windows 10

**Comment by ximion** [comment]
Yeah, that's an extremely odd bug on Windows (doesn#t happen on Linux for some reason). It can be worked around easily though: Just move your cursor to the right of the window until you get the splitter handle, and then move the splitter to the right so the display panel is visible again.
The issue is solely that the configurations column width is set too wide. The software is actually supposed to save user preferences here, but somehow fails to restore them on Windows.
